---
- name: update the system
  become: yes
  yum:
    name: "*"
    state: latest

- name: install epel-release
  become: yes
  yum: 
    name: epel-release
    state: latest

- name: install haproxy
  become: yes
  yum:
    name: haproxy
    state: present